import { Templates } from '../module/utils/constants';

export const preloadTemplates = () => {
  const templatePaths = [
    Templates.Dialog.ModDialog,
    Templates.Dialog.DamageCalculator,
    Templates.Dialog.newSupernaturalShield.main,
    Templates.Dialog.newSupernaturalShield.parts.mystic,
    Templates.Dialog.newSupernaturalShield.parts.psychic,
    Templates.Dialog.Combat.CombatAttackDialog.main,
    Templates.Dialog.Combat.CombatAttackDialog.parts.combat,
    Templates.Dialog.Combat.CombatAttackDialog.parts.mystic,
    Templates.Dialog.Combat.CombatAttackDialog.parts.psychic,
    Templates.Dialog.Combat.CombatDefenseDialog.main,
    Templates.Dialog.Combat.CombatDefenseDialog.parts.combat,
    Templates.Dialog.Combat.CombatDefenseDialog.parts.damageResistance,
    Templates.Dialog.Combat.CombatDefenseDialog.parts.mystic,
    Templates.Dialog.Combat.CombatDefenseDialog.parts.psychic,
    Templates.Dialog.Combat.CombatRequestDialog,
    Templates.Dialog.Combat.GMCombatDialog,
    Templates.Dialog.Icons.Accept,
    Templates.Dialog.Icons.Cancel,
    Templates.CustomHotBar,
    Templates.Chat.CombatResult,

    // Common parts
    'systems/abf/templates/common/ui/horizontal-titled-input.hbs',
    'systems/abf/templates/common/ui/vertical-titled-input.hbs',
    'systems/abf/templates/common/ui/group.hbs',
    'systems/abf/templates/common/ui/group-header.hbs',
    'systems/abf/templates/common/ui/group-header-title.hbs',
    'systems/abf/templates/common/ui/group-body.hbs',
    'systems/abf/templates/common/ui/group-footer.hbs',
    'systems/abf/templates/common/ui/add-item-button.hbs',
    'systems/abf/templates/common/ui/custom-select.hbs',
    'systems/abf/templates/common/ui/custom-select-choices.hbs',
    'systems/abf/templates/common/ui/loading-indicator.hbs',

    // Domain parts
    'systems/abf/templates/common/domain/weapon/one-or-two-handed.hbs',
    'systems/abf/templates/common/domain/weapon/knowledge-type.hbs',
    'systems/abf/templates/common/domain/weapon/select-ammo.hbs',
    'systems/abf/templates/common/domain/armor/select-armor-type.hbs',
    'systems/abf/templates/common/domain/armor/select-armor-localization.hbs',
    'systems/abf/templates/common/domain/select-quality.hbs',

    // Items sheet parts
    'systems/abf/templates/items/base/base-sheet.hbs',
    'systems/abf/templates/items/base/parts/item-image.hbs',
    'systems/abf/templates/items/weapon/weapon.hbs',
    'systems/abf/templates/items/ammo/ammo.hbs',
    'systems/abf/templates/items/armor/armor.hbs',
    'systems/abf/templates/items/spell/spell.hbs',
    'systems/abf/templates/items/psychicPower/psychicPower.hbs',

    // Actor sheet parts
    'systems/abf/templates/actor/parts/header/header.hbs',
    'systems/abf/templates/actor/parts/header/parts/top.hbs',
    'systems/abf/templates/actor/parts/header/parts/actor-image.hbs',
    'systems/abf/templates/actor/parts/header/parts/total-armor.hbs',
    'systems/abf/templates/actor/parts/header/parts/common-resources.hbs',
    'systems/abf/templates/actor/parts/header/parts/modifiers.hbs',
    'systems/abf/templates/actor/parts/header/parts/primary-characteristics.hbs',
    'systems/abf/templates/actor/parts/header/parts/resistances.hbs',
    'systems/abf/templates/actor/parts/general/general.hbs',
    'systems/abf/templates/actor/parts/general/parts/level.hbs',
    'systems/abf/templates/actor/parts/general/parts/language.hbs',
    'systems/abf/templates/actor/parts/general/parts/elan.hbs',
    'systems/abf/templates/actor/parts/general/parts/titles.hbs',
    'systems/abf/templates/actor/parts/general/parts/destiny-points.hbs',
    'systems/abf/templates/actor/parts/general/parts/presence.hbs',
    'systems/abf/templates/actor/parts/general/parts/experience.hbs',
    'systems/abf/templates/actor/parts/general/parts/advantages.hbs',
    'systems/abf/templates/actor/parts/general/parts/disadvantages.hbs',
    'systems/abf/templates/actor/parts/general/parts/aspect.hbs',
    'systems/abf/templates/actor/parts/general/parts/description.hbs',
    'systems/abf/templates/actor/parts/general/parts/regeneration.hbs',
    'systems/abf/templates/actor/parts/general/parts/contacts.hbs',
    'systems/abf/templates/actor/parts/general/parts/notes.hbs',
    'systems/abf/templates/actor/parts/general/parts/inventory-items.hbs',
    'systems/abf/templates/actor/parts/general/parts/money.hbs',
    'systems/abf/templates/actor/parts/secondaries/secondaries.hbs',
    'systems/abf/templates/actor/parts/secondaries/common/secondary-skill.hbs',
    'systems/abf/templates/actor/parts/secondaries/parts/athletics.hbs',
    'systems/abf/templates/actor/parts/secondaries/parts/vigor.hbs',
    'systems/abf/templates/actor/parts/secondaries/parts/perception.hbs',
    'systems/abf/templates/actor/parts/secondaries/parts/intellectual.hbs',
    'systems/abf/templates/actor/parts/secondaries/parts/subterfuge.hbs',
    'systems/abf/templates/actor/parts/secondaries/parts/social.hbs',
    'systems/abf/templates/actor/parts/secondaries/parts/creative.hbs',
    'systems/abf/templates/actor/parts/secondaries/parts/secondary-special-skills.hbs',
    'systems/abf/templates/actor/parts/combat/combat.hbs',
    'systems/abf/templates/actor/parts/combat/parts/base-values.hbs',
    'systems/abf/templates/actor/parts/combat/parts/combat-special-skills.hbs',
    'systems/abf/templates/actor/parts/combat/parts/combat-tables.hbs',
    'systems/abf/templates/actor/parts/combat/parts/ammo.hbs',
    'systems/abf/templates/actor/parts/combat/parts/armors.hbs',
    'systems/abf/templates/actor/parts/combat/parts/weapons.hbs',
    'systems/abf/templates/actor/parts/combat/parts/supernatural-shields.hbs',
    'systems/abf/templates/actor/parts/mystic/mystic.hbs',
    'systems/abf/templates/actor/parts/mystic/parts/act.hbs',
    'systems/abf/templates/actor/parts/mystic/parts/magic-projection.hbs',
    'systems/abf/templates/actor/parts/mystic/parts/zeon-regeneration.hbs',
    'systems/abf/templates/actor/parts/mystic/parts/innate-magic.hbs',
    'systems/abf/templates/actor/parts/mystic/parts/zeon.hbs',
    'systems/abf/templates/actor/parts/mystic/parts/mystic-settings.hbs',
    'systems/abf/templates/actor/parts/mystic/parts/summoning.hbs',
    'systems/abf/templates/actor/parts/mystic/parts/spheres.hbs',
    'systems/abf/templates/actor/parts/mystic/parts/spells/spells.hbs',
    'systems/abf/templates/actor/parts/mystic/parts/spells/grade/grade.hbs',
    'systems/abf/templates/actor/parts/mystic/parts/spell-maintenances.hbs',
    'systems/abf/templates/actor/parts/mystic/parts/selected-spells.hbs',
    'systems/abf/templates/actor/parts/mystic/parts/prepared-spells.hbs',
    'systems/abf/templates/actor/parts/mystic/parts/summons.hbs',
    'systems/abf/templates/actor/parts/mystic/parts/metamagics.hbs',
    'systems/abf/templates/actor/parts/domine/domine.hbs',
    'systems/abf/templates/actor/parts/domine/parts/ki-skills.hbs',
    'systems/abf/templates/actor/parts/domine/parts/nemesis-skills.hbs',
    'systems/abf/templates/actor/parts/domine/parts/ars-magnus.hbs',
    'systems/abf/templates/actor/parts/domine/parts/martial-arts.hbs',
    'systems/abf/templates/actor/parts/domine/parts/creatures.hbs',
    'systems/abf/templates/actor/parts/domine/parts/special-skills-tables.hbs',
    'systems/abf/templates/actor/parts/domine/parts/ki-accumulation.hbs',
    'systems/abf/templates/actor/parts/domine/parts/martial-knowledge.hbs',
    'systems/abf/templates/actor/parts/domine/parts/seals.hbs',
    'systems/abf/templates/actor/parts/domine/parts/techniques.hbs',
    'systems/abf/templates/actor/parts/psychic/psychic.hbs',
    'systems/abf/templates/actor/parts/psychic/parts/psychic-potential.hbs',
    'systems/abf/templates/actor/parts/psychic/parts/psychic-projection.hbs',
    'systems/abf/templates/actor/parts/psychic/parts/mental-patterns.hbs',
    'systems/abf/templates/actor/parts/psychic/parts/innate-psychic-powers.hbs',
    'systems/abf/templates/actor/parts/psychic/parts/psychic-points.hbs',
    'systems/abf/templates/actor/parts/psychic/parts/psychic-settings.hbs',
    'systems/abf/templates/actor/parts/psychic/parts/psychic-disciplines.hbs',
    'systems/abf/templates/actor/parts/psychic/parts/psychic-powers.hbs',
    'systems/abf/templates/actor/parts/settings/settings.hbs',
    'systems/abf/templates/actor/parts/settings/parts/tabVisibility.hbs',
    'systems/abf/templates/actor/parts/settings/parts/automationOptions.hbs',
    'systems/abf/templates/actor/parts/settings/parts/advancedSettings.hbs',
    'systems/abf/templates/actor/parts/settings/parts/advancedCharacteristics.hbs'
  ];

  return loadTemplates(templatePaths);
};
