export const ABFSettingsKeys = {
  AUTO_ACCEPT_COMBAT_REQUESTS: 'AUTO_ACCEPT_COMBAT_REQUESTS',
  ROUND_DAMAGE_IN_MULTIPLES_OF_5: 'ROUND_DAMAGE_IN_MULTIPLES_OF_5',
  SEND_ROLL_MESSAGES_ON_COMBAT_BY_DEFAULT: 'SEND_ROLL_MESSAGES_ON_COMBAT_BY_DEFAULT',
  USE_DAMAGE_TABLE: 'USE_DAMAGE_TABLE',
  DEVELOP_MODE: 'DEVELOP_MODE',
  AUTOMATE_COMBAT_DISTANCE: 'AUTOMATE_COMBAT_DISTANCE',
  MACRO_PREFIX_ATTACK: 'MACRO_PREFIX_ATTACK',
  MACRO_ATTACK_DEFAULT: 'MACRO_ATTACK_DEFAULT',
  MACRO_PROJECTILE_DEFAULT: 'MACRO_PROJECTILE_DEFAULT',
  MACRO_SHIELD_DEFAULT: 'MACRO_SHIELD_DEFAULT',
  MACRO_MISS_ATTACK_VALUE: 'MACRO_MISS_ATTACK_VALUE',
  APPLIED_MIGRATIONS: 'APPLIED_MIGRATIONS',
  WORLD_CREATION_SYSTEM_VERSION: 'WORLD_CREATION_SYSTEM_VERSION',
  MODIFY_DICE_FORMULAS_PERMISSION: 'MODIFY_DICE_FORMULAS_PERMISSION'
};
